service: loginWithLink
frameworkVersion: '3'

provider:
  name: aws
  environment:
    stageEnv: ${self:custom.stage}
    ACCOUNT_NUMBER: ${self:custom.account.${self:custom.stage}}
    COGNITO_ARN: ${self:custom.cognitoArn.${self:custom.stage}}
    NAME_API_GATEWAY: ${self:custom.apiGatewayName.${self:custom.stage}}
    COGNITO_USER_POOL: ${self:custom.cognitoUserPool.${self:custom.stage}}
  runtime: nodejs16.x
  architecture: arm64
  lambdaHashingVersion: 20201221
  stage: ${self:custom.stage}
  region: 'us-east-1'
  memorySize: 256
  timeout: 15
  iam:
    role:
      name: 'loginWithLinkLambdaRole'
      statements: 
      - Effect: Allow
        Action:
          - kms:*
        Resource: 
          - "arn:aws:kms:sa-east-1:${self:custom.account.${self:custom.stage}}:key/*"
      - Effect: Allow
        Action:
          - ssm:DescribeParameters
          - ssm:GetParameter
          - ssm:GetParameters
        Resource: 
          - "*"

custom:
  stage: ${opt:stage, 'dev'}
  account:
    prd: ''
    hml: ''
    dev: ''
  apiGatewayName:
    dev: '???'
    hml: '???'
    prd: '???'
  secretManagerName:
    dev: '???'
    hml: '???'
    prd: '???'
  secret: ${ssm(us-east-1):/aws/reference/secretsmanager/${self:custom.secretManagerName.${self:custom.stage}}}

functions:
  event:
    handler: event.handler